id: I13141992
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T01:44:56+00:00'
last_modified: '2022-06-08T16:34:39.050889+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29238
  title: དགག་སྒྲུབ་སྙིང་སྟོབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4D10:
      image_group_id: I5545
      title: ''
      total_pages: 320
      order: 1
      base_file: 4D10.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
