id: P010659
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:18:37.757403
source_metadata:
  id: bdr:W29238
  title: དགག་སྒྲུབ་སྙིང་སྟོབས
  author: ''
  volumes:
    80ef50c10a8a40d9911be5de37bf6563:
      image_group_id: I5545
      title: ''
      volume_number: 1
      total_pages: 320
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
